import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContext } from "@/context";
import Navbar from "@/components/shared/Navbar";
import { Suspense } from "react";
import Loading from "./loading";
import ScrollTop from "@/components/shared/ScrollTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mozahid - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <ThemeContext>
          <Navbar />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <div id="modal-root-content" />
          <ScrollTop />
        </ThemeContext>
      </body>
    </html>
  );
}
